### ISSUE TITLE
Dear developers, can you make a Legends of Azeroth-Pandaria-5.4.8 docker version?

### ISSUE THREAD

**Issue by hua445633972** [diff3/pandaria_5.4.8_docker#1]
Respect of developers, I am a novice, you can give a version of https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8? Thank you very much

**Comment by diff3** [comment]
it's just me, and I think I got a docker on my main computer. not sure how updated it is. I upload it tomorrow

**Comment by diff3** [comment]
https://github.com/diff3/Legends_of_Azaroth_docker

**Comment by diff3** [comment]
done
